### ISSUE TITLE
Failure to compute gradient

### ISSUE THREAD

**Issue by rschwarz15** [loeweX/Greedy_InfoMax#10]
Hi,

I have found your paper and code extremely interesting!

I am trying to run the vision training, but am coming across an error:

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 256, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

When I do torch.autograd.set_detect_anomaly(True) the issue is traced to line 57 in InfoNCE_Loss:

https://github.com/loeweX/Greedy_InfoMax/blob/8f91dc27fcc6edf1f5b9f005a9f5566bb796dce2/GreedyInfoMax/vision/models/InfoNCE_Loss.py#L55-L57

Any idea why this is hapenning?

**Comment by loeweX** [comment]
Hi,

Thank you for your interest in our work!

I haven't encountered that error before, so I cannot give a definite answer. My guess would be that it could have something to do with the pytorch version that you are using. Did you make sure to use version 1.0.0?

Alternatively, have you tried following the advice in [this article](https://medium.com/@nieznanm/runtimeerror-one-of-the-variables-needed-for-gradient-computation-has-been-modified-by-an-inplace-85d0d207623)?

**Comment by rschwarz15** [comment]
Right, I'd had a conflict error in the environment set up and had changed it to PyTorch 1.5
