### ISSUE TITLE
Resnet Encoder Layer Numbers

### ISSUE THREAD

**Issue by rschwarz15** [loeweX/Greedy_InfoMax#12]
With the Pre-activation ResNet Encoders that are used, my understanding of the layer numbers doesn't align with how you've labelled them. 

https://github.com/loeweX/Greedy_InfoMax/blob/8f91dc27fcc6edf1f5b9f005a9f5566bb796dce2/GreedyInfoMax/vision/models/FullModel.py#L27-L36

The total number of blocks in block_dims is 37 and there is also the initial conv1. When using PreActBlockNoBN, 2 layers per block, does this not result in a ResNet75? When using PreActBottleneckNoBN, 3 layers per block, does this not result in a ResNet112?

Please let me know if I've misunderstood something.

**Comment by loeweX** [comment]
Good catch! Indeed, it should be:

```python
block_dims = [3, 4, 6] 
num_channels = [64, 128, 256] 
```

(Since we're only considering the first four blocks of the ResNet architecture)

Could you submit a pull request?
