### ISSUE TITLE
The following problem occurred when I was building the model following the READme.md file. Is there any problem with the function InfoNCE_Loss？

### ISSUE THREAD

**Issue by SImpleIII** [loeweX/Greedy_InfoMax#16]
The problem : RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 6144]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by loeweX** [comment]
Hi! 
This problem occurs when using newer versions of Pytorch. You can either try to manually install Pytorch 1.0.0, or make use of this pull request which should fix the problem for newer versions: [https://github.com/loeweX/Greedy_InfoMax/pull/15](https://github.com/loeweX/Greedy_InfoMax/pull/15)
