### ISSUE TITLE
Pre-trained vision model?

### ISSUE THREAD

**Issue by nikparth** [loeweX/Greedy_InfoMax#19]
Hi! Is there a pre-trained vision model available somewhere? It would be really helpful instead of having to re-train the model from scratch. 

Thanks!
Nikhil

**Comment by loeweX** [comment]
Hi,

Luckily, I still had this model lying around somewhere - I've uploaded it [here](https://drive.google.com/file/d/1yxwVOpxlrdAFHrNtMYy4QkszsUQFrI6X/view?usp=sharing). Does this work for you?

Best,
Sindy

**Comment by nikparth** [comment]
Hi yes that works great thank you very much! 

Best,
Nikhil

**Comment by nikparth** [comment]
Hi Sindy, 
Sorry to bother you again, but I downloaded the checkpoint but had not tried loading it in and I seem to be getting a "MemoryError" when using torch.load() with that checkpoint? I have more than enough memory, so I'm wondering what the issue might be- if you have any idea that would be great but if it's too much trouble the no worries, I'll just try training from scratch. 

Thanks,
Nikhil

**Comment by loeweX** [comment]
Hi Nikhil,

I'm afraid I cannot help you with that. I've tried it on my machine, and there things work without a problem.

Best,
Sindy
