### ISSUE TITLE
Audio training time

### ISSUE THREAD

**Issue by cfoster0** [loeweX/Greedy_InfoMax#9]
What should be the training time (as in time per step, per epoch, or time to convergence) for the audio experiment? I'm running it on a Tesla K80 and it seems to be taking ~5.7 seconds _per step_, which I'm assuming is much slower than expected.

**Comment by loeweX** [comment]
Hi,

Did you try setting the command line argument --subsample as in audio_traineval.sh? This can reduce the training time by a big margin.

**Comment by cfoster0** [comment]
Yeah, this is running audio_traineval.sh.
